feat: Story map collaboration pending state
techmatters/terraso-web-client pull request #1133
Opened 2023-08-22 19:27 UTC by josebui

## Description

- Added Story map collaboration pending state
- Added support for invites for not registered users

### Checklist
- [ ] Corresponding issue has been opened
- [ ] New tests added

### Related Issues
Fixes #....

### Verification steps

2023-08-30 18:18 UTC, paulschreiber requested changes

2023-08-30 18:18 UTC, paulschreiber commented on src/collaboration/components/MemberName.js
> +import React from 'react';
issue: add copyright notice.

2023-08-30 18:18 UTC, paulschreiber commented on src/collaboration/collaborationConstants.js
> +export const MEMBERSHIP_STATUS_APPROVED = 'APPROVED';
issue: add copyright notice.

2023-08-30 18:18 UTC, paulschreiber commented on src/collaboration/components/MembershipsList.js
> +import React, { useMemo } from 'react';
issue: add copyright notice.

2023-08-30 18:18 UTC, paulschreiber commented on src/tests/uiUtils.js
> +import { fireEvent, within } from 'tests/utils';
issue: add copyright notice.

2023-08-30 18:18 UTC, paulschreiber commented on src/tests/apiUtils.js
> +import * as terrasoApi from 'terraso-client-shared/terrasoApi/api';
issue: add copyright notice.

2023-08-30 18:18 UTC, paulschreiber commented on src/localization/i18n.js
> +
suggestion: use `Intl.ListFormat` https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat

2023-08-30 18:18 UTC, paulschreiber commented on src/localization/locales/en-US.json
> +        "share_dialog_autocomplete_helper_text": "The person you invite will receive an email invitation to join this story map in a few minutes.",
```suggestion
        "share_dialog_autocomplete_helper_text": "They will receive an email invitation to join this story map.",
```

2023-09-05 14:42 UTC, paulschreiber requested changes

2023-09-05 14:42 UTC, paulschreiber commented on src/localization/i18n.js
> +i18n.services.formatter.add('andList', (value, lng, options) => {
question: can we use [i18n's built-in list support?](https://www.i18next.com/translation-function/formatting#list) 
```
// JSON
{
  "intlList": "A list of {{val, list}}"
}

i18next.t('intlList', { val: ['locize', 'i18next', 'awesomeness'] });
// --> A list of locize, i18next, and awesomeness
```

2023-09-05 16:08 UTC, paulschreiber approved these changes

2023-09-05 22:46 UTC, shrouxm commented on src/storyMap/storyMapService.js
> +    })
nit: in other mutations, we do this which has less code dup (applies to several mutations in this file):
```suggestion
  const query = graphql(`
    mutation addMemberships($input: StoryMapMembershipSaveMutationInput!) {
      saveStoryMapMembership(input: $input) {
        memberships {
          ...collaborationMembershipFields
        }
        errors
      }
    }
  `);

  return terrasoApi
    .requestGraphQL(query, {
      input: {
        storyMapId: storyMap.storyMapId,
        storyMapSlug: storyMap.slug,
        userEmails: emails,
        userRole,
      },
    })
```

2023-09-11 19:58 UTC, merged