refactor: Landscape membership list
techmatters/terraso-web-client pull request #1262
Opened 2023-11-01 14:44 UTC by josebui

## Description

Landscape is using a group to handle the user memberships in this PR I changed it to use MembershipList to removing the dependency with Group

### Checklist
- [ ] Corresponding issue has been opened
- [ ] New tests added

### Related Issues
Fixes #....

### Verification steps

2023-11-02 01:32 UTC, paulschreiber requested changes

2023-11-02 01:32 UTC, paulschreiber commented on src/collaboration/components/MemberJoin.js
> + * Copyright © 2021-2023 Technology Matters
```suggestion
 * Copyright © 2023 Technology Matters
```

2023-11-02 01:32 UTC, paulschreiber commented on src/collaboration/collaborationContext.js
> + * Copyright © 2021-2023 Technology Matters
```suggestion
 * Copyright © 2023 Technology Matters
```

2023-11-02 01:32 UTC, paulschreiber commented on src/collaboration/components/MembershipCard.js
> + * Copyright © 2021-2023 Technology Matters
```suggestion
 * Copyright © 2023 Technology Matters
```

2023-11-02 01:32 UTC, paulschreiber commented on src/collaboration/components/MembershipCard.js
> +    accountMembership.membershipStatus === MEMBERSHIP_STATUS_PENDING;
```suggestion
  const pendingRequest =
    accountMembership?.membershipStatus === MEMBERSHIP_STATUS_PENDING;
```

2023-11-02 01:32 UTC, paulschreiber commented on src/collaboration/components/MembershipCount.js
> + * Copyright © 2021-2023 Technology Matters
```suggestion
 * Copyright © 2023 Technology Matters
```

2023-11-02 01:32 UTC, paulschreiber commented on src/collaboration/components/MembershipJoinLeaveButton.js
> + * Copyright © 2021-2023 Technology Matters
```suggestion
 * Copyright © 2023 Technology Matters
```

2023-11-02 01:32 UTC, paulschreiber commented on src/collaboration/components/MembershipJoinLeaveButton.js
> +    accountMembership.membershipStatus === MEMBERSHIP_STATUS_PENDING
```suggestion
    accountMembership?.membershipStatus === MEMBERSHIP_STATUS_PENDING
```

2023-11-02 01:32 UTC, paulschreiber commented on src/collaboration/components/MembershipPendingWarning.js
> + * Copyright © 2021-2023 Technology Matters
```suggestion
 * Copyright © 2023 Technology Matters
```

2023-11-02 01:32 UTC, paulschreiber commented on src/collaboration/components/RoleSelect.js
> +import React, { useCallback } from 'react';
issue: add copyright notice.

2023-11-02 01:32 UTC, paulschreiber commented on src/landscape/landscapeService.js
> +} from './landscapeConstants';
issue: do not use relative path.

2023-11-07 17:09 UTC, josebui commented on src/landscape/landscapeSlice.js
> +      })
@paulschreiber IMO your suggestion is better

2023-11-21 22:45 UTC, josebui commented
The final PR is: https://github.com/techmatters/terraso-web-client/pull/1317

2023-11-21 22:45 UTC, closed without merging