feat: Display user profile image
techmatters/terraso-web-client pull request #149
Opened 2022-01-12 21:39 UTC by josebui

## Description

- Display User profile image

### Checklist
- [ ] Corresponding issue has been opened
- [ ] New tests added
- [ ] Strings are localized
- [ ] Verified on mobile
- [ ] Verified on desktop

### Related Issues
Fixes #123 

### Verification steps

Screenshots:
![download (21)](https://user-images.githubusercontent.com/1316782/149225278-2ef0fbd3-1524-48fc-98cd-9d38b67fcb1a.png)
![download (20)](https://user-images.githubusercontent.com/1316782/149225280-b4a8f3a4-4332-47ba-b035-581c815dfcf7.png)

2022-01-12 22:50 UTC, paulschreiber requested changes

2022-01-12 22:50 UTC, paulschreiber commented on src/account/components/AccountProfile.test.js
> +          firstName: 'Jhon',
issue: you probably wanted `John` here (and in a few other places).

2022-01-13 00:07 UTC, cacarrara approved these changes

2022-01-13 15:18 UTC, paulschreiber approved these changes

2022-01-13 15:18 UTC, merged