fix: Redirect user to complete profile after first login
techmatters/terraso-web-client pull request #1622
Opened 2024-03-11 18:42 UTC by josebui

## Description

- Redirect user to complete profile after first login
- Stored a new value in local storage to know if the user has already viewed the profile page after the first login

### Checklist
- [ ] Corresponding issue has been opened
- [ ] New tests added

### Related Issues
- https://github.com/techmatters/terraso-web-client/issues/1145

2024-03-11 20:57 UTC, paulschreiber approved these changes

2024-03-11 20:57 UTC, paulschreiber commented on src/account/components/AccountProfile.js
> +
question: why is this doubly nested?

2024-03-11 21:02 UTC, paulschreiber requested changes
@josebui Please add the missing translation.

2024-03-12 16:11 UTC, paulschreiber approved these changes

2024-03-12 16:11 UTC, paulschreiber commented on src/localization/locales/es-ES.json
> +        "profile_complete_message": "Sólo necesitamos algunos detalles sobre ti antes de que poder comenzar.",
```suggestion
        "profile_complete_message": "Necesitamos algunos detalles sobre ti antes de que poder comenzar.",
```

2024-03-12 16:23 UTC, paulschreiber commented on src/localization/locales/en-US.json
> +        "profile_complete_message": "We just need a few details about you before you can get started.",
Let us know what to call you, and what language you’d like to use.

2024-03-12 16:54 UTC, paulschreiber commented on src/localization/locales/en-US.json
> +        "profile_complete_message": "We just need a few details about you before you can get started.",
```suggestion
        "profile_complete_message": "Tell us what to call you and review your profile settings.",
```

2024-03-12 18:32 UTC, paulschreiber approved these changes

2024-03-14 17:33 UTC, paulschreiber approved these changes

2024-03-15 20:20 UTC, paulschreiber commented on src/account/components/AccountProfile.js
> +      promise => !!promise
```suggestion
      promise => Boolean(promise)
```

2024-03-19 14:51 UTC, josebui commented on src/account/accountProfileUtils.js
> +    if (location?.pathname.includes('/account/profile/completeProfile')) {
I think includes makes more sense

2024-03-19 18:40 UTC, paulschreiber approved these changes

2024-03-19 18:41 UTC, merged