feat: Change story map style
techmatters/terraso-web-client pull request #1767
Opened 2024-04-11 20:34 UTC by josebui

## Description

### Checklist
- [ ] Corresponding issue has been opened
- [ ] New tests added

### Related Issues
Fixes #....

### Verification steps

2024-04-12 18:41 UTC, paulschreiber requested changes
- Remove the confirmation dialog — change immediately.
- Switching layers give 404 errors — please confirm the style URLs and that the styles are public.
- Satellite and detailed satellite are too similar. Once I can see what they actually are, I will give better name suggestions.

2024-04-12 20:02 UTC, josebui commented on src/storyMap/components/StoryMapForm/MapLocationDialog.js
> +    const location = _.omitBy(_.isNil, {
@paulschreiber Just null or undifined, some of these values are numbers so the could include the `0` falsy value

2024-04-12 20:03 UTC, josebui commented
> Switching layers give 404 errors — please confirm the style URLs and that the styles are public.

@paulschreiber Where do you see that error?, seems to be working locally and on staging for me

2024-04-12 20:03 UTC, josebui commented
> Remove the confirmation dialog — change immediately.

@paulschreiber Can you add more context about this?

2024-04-15 19:05 UTC, paulschreiber commented on src/storyMap/components/StoryMapForm/MapLocationDialog.js
> +    const location = _.omitBy(_.isNil, {
What about `false`?

2024-04-17 21:30 UTC, paulschreiber approved these changes

2024-04-18 01:26 UTC, merged