feat: API error messages
techmatters/terraso-web-client pull request #262
Opened 2022-03-10 20:35 UTC by josebui

## Description

### Checklist
- [ ] Corresponding issue has been opened
- [ ] New tests added
- [ ] Strings are localized

### Related Issues
Fixes #....

### Verification steps

2022-03-11 19:32 UTC, paulschreiber requested changes

2022-03-11 19:45 UTC, josebui commented on src/localization/locales/en-US.json
> +        "updateNotAllowed": "$t(terraso_api.updateNotAllowed_base)",
@paulschreiber For this one the code is coming from the API as `deleteNotAllowed` so we will have to programatically change it to snake cased, IMO is not worth it, waht do you think?

2022-03-11 19:47 UTC, paulschreiber commented on src/localization/locales/en-US.json
> +        "updateNotAllowed": "$t(terraso_api.updateNotAllowed_base)",
If we can't change what the API returns, then we can leave as-is.

2022-03-11 20:17 UTC, josebui commented on src/localization/locales/en-US.json
> +        "updateNotAllowed": "$t(terraso_api.updateNotAllowed_base)",
That makes sense, I will check the API

2022-03-14 20:47 UTC, josebui commented on src/localization/locales/en-US.json
> +        "delete_not_allowed_manager_count": "$t(terraso_api.delete_not_allowed_base). There should at least be one manager."
@paulschreiber It just calls the other key, you can also pass paramters to it: you can check that here: https://www.i18next.com/translation-function/nesting

2022-03-14 20:50 UTC, merged