feat: Represent dataset in a map
techmatters/terraso-web-client pull request #532
Opened 2022-09-12 15:32 UTC by josebui

## Description

- Represent dataset in a map feature

### Checklist
- [ ] Corresponding issue has been opened
- [ ] New tests added

### Related Issues
Fixes #....

### Verification steps

2022-09-20 19:14 UTC, paulschreiber requested changes
You're also missing useDocumentTitle() on the visualization pages.

2022-09-20 19:14 UTC, paulschreiber commented on src/sharedData/visualization/components/VisualizationWrapper.js
> +  );
issue: this function is written out three times. Move it to a utils file.

2022-09-20 19:14 UTC, paulschreiber commented on src/sharedData/visualization/components/VisualizationConfigForm/index.js
> +    color: '#A96F14',
issue: this color should come from theme.js

2022-09-20 19:20 UTC, josebui commented on package.json
> +    "xlsx": "https://cdn.sheetjs.com/xlsx-0.18.10/xlsx-0.18.10.tgz",
@paulschreiber this is the reason:

https://docs.sheetjs.com/docs/getting-started/installation/nodejs
 
![image](https://user-images.githubusercontent.com/1316782/191345778-f19dca06-655b-432c-949f-1f84ed11f385.png)

2022-09-20 19:22 UTC, josebui commented on src/sharedData/visualization/visualizationUtils.js
> +import * as SheetsJs from 'xlsx';
@paulschreiber I think that can be a potential improvement, but right now that is not the way the other files like this are named, so I don't think we should do this change as part of this PR

2022-09-20 19:25 UTC, paulschreiber commented on src/sharedData/visualization/visualizationUtils.js
> +import * as SheetsJs from 'xlsx';
I hadn't noticed that. Having visualizationXYZ inside visualization is redundant. We should fix them all.

2022-09-20 19:45 UTC, josebui commented on src/sharedData/visualization/components/VisualizationConfigForm/SelectDataFileStep.js
> +            help link
@paulschreiber Can you add more context to this? Most of the strings still need to be localized to spanish

2022-09-20 20:30 UTC, paulschreiber commented on src/sharedData/visualization/components/VisualizationConfigForm/SelectDataFileStep.js
> +            help link
You have the bare strings i.e. `Recommentation` and no `t()` call.

2022-09-20 20:35 UTC, josebui commented on src/sharedData/visualization/components/VisualizationConfigForm/SelectDataFileStep.js
> +            help link
@paulschreiber this is wrapped with by a `Trans` component, this content is localized

2022-09-20 20:36 UTC, josebui commented on src/sharedData/visualization/visualizationUtils.js
> +import * as SheetsJs from 'xlsx';
@paulschreiber We can talk about that for future improvements, it is not a trivial decision, and defenitely not in the scope of this feature, that will be a lot of files changed outside of this

2022-09-20 20:40 UTC, paulschreiber requested changes
Fix spelling of strings in <Trans>

2022-09-20 20:40 UTC, paulschreiber commented on src/sharedData/visualization/components/VisualizationConfigForm/SelectDataFileStep.js
> +          <li>Requirment 2</li>
```suggestion
          <li>Requirement 1</li>
          <li>Requirement 2</li>
```

2022-09-20 20:40 UTC, paulschreiber commented on src/sharedData/visualization/components/VisualizationConfigForm/SelectDataFileStep.js
> +          Recommentation
```suggestion
          Recommendation
```

2022-09-28 16:38 UTC, josebui commented on src/localization/locales/en-US.json
> +        "addVisualizationConfig.unique": "[TODO] The title “{{body.variables.input.title}}“ is being used by other map, change it and try again."
@paulschreiber Can you review this string? This is the message the user will see when the title is already being used by other map

2022-09-28 17:42 UTC, paulschreiber approved these changes

2022-09-28 17:42 UTC, paulschreiber commented on src/localization/locales/en-US.json
> +        "addVisualizationConfig.unique": "[TODO] The title “{{body.variables.input.title}}“ is being used by other map, change it and try again."
```suggestion
        "addVisualizationConfig.unique": "The name “{{body.variables.input.title}}“ is in use by another map. Please use a different name."
```

2022-09-28 19:55 UTC, merged