feat: Added profile and affiliation step to new form
techmatters/terraso-web-client pull request #576
Opened 2022-10-13 17:22 UTC by josebui

## Description

### Checklist
- [ ] Corresponding issue has been opened
- [ ] New tests added
- [ ] English strings reviewed and copyedited
- [ ] Strings are localized
- [ ] Verified on mobile
- [ ] Verified on desktop
- [ ] Verified accessibility ([Accessibility - Web applications](https://docs.google.com/document/d/1VwPDyLqw7r_iISMgDZr1FdAmAqqOIIVIxQqsYA-HaHE/edit?usp=sharing))

### Related Issues
Fixes #564

2022-10-17 16:52 UTC, david-code requested changes

2022-10-17 16:52 UTC, david-code commented on src/landscape/components/LandscapeForm/AffiliationStep.js
> +  console.log({ setUpdatedLandscape, landscape, isNew });
chore: get rid of console.log
```suggestion
```

2022-10-17 21:28 UTC, josebui commented on src/landscape/components/LandscapeForm/InfoStep.js
> +  const { setUpdatedLandscape, landscape, isNew } = props;
@david-code In that case `isNew` will be falsy, so not really React magic more a Javascript thing

2022-10-17 21:29 UTC, josebui commented on src/landscape/components/LandscapeForm/ProfileStep.js
> +  console.log({ setUpdatedLandscape, landscape, isNew });
@david-code This Step needs to be finished as part of other Issues what is why this temporary console.log is here

2022-10-17 21:29 UTC, josebui commented on src/landscape/components/LandscapeForm/AffiliationStep.js
> +  console.log({ setUpdatedLandscape, landscape, isNew });
@david-code same here

2022-10-18 14:06 UTC, paulschreiber requested changes

2022-10-18 14:06 UTC, paulschreiber commented on src/landscape/components/LandscapeForm/ProfileStep.js
> +    </Stack>
Suggestion. This looks very similar to what's in `AffiliationStep.js`. Make this into a component that you reuse.

2022-10-19 16:53 UTC, paulschreiber requested changes
This looks pretty good.

issue: please fix the tests so they pass.

2022-10-19 21:40 UTC, josebui commented
@paulschreiber This are intermidiate steps for the complete feature, I will not be fixing tests at this stage since a lot of things might change after

2022-10-20 15:32 UTC, paulschreiber approved these changes

2022-10-20 16:01 UTC, merged