feat: Landscape profile image
techmatters/terraso-web-client pull request #598
Opened 2022-11-09 17:29 UTC by josebui

## Description

- Landscape Profile Image update form
- Landscape Profile Image display in profile page

### Checklist
- [ ] Corresponding issue has been opened
- [ ] New tests added

### Related Issues
Fixes #573

### Verification steps

2022-11-11 17:13 UTC, david-code reviewed
Looks good to me! I will let Paul take a look as well.

2022-11-14 15:11 UTC, josebui commented on src/landscape/components/LandscapeForm/ProfileImageStep.js
> +    });
@david-code Thanks David, and from your comment I realized that there is more code that can be reused between openImage and openFile

2022-11-14 15:11 UTC, josebui commented on src/landscape/components/LandscapeForm/ProfileImageStep.js
> +              const height = (width * 9) / 16;
@david-code I came from the Figam designs, and I agree I will move this to a constant

2022-11-15 04:27 UTC, paulschreiber commented on src/landscape/components/LandscapeProfile/ProfileCard.js
> +import profileImageDefault from './profile-image-default.jpg';
question: can this go in `public` with the other images?

2022-11-15 04:27 UTC, paulschreiber commented on src/landscape/components/LandscapeForm/ProfileImageStep.js
> +  const [size, setSize] = useState({ width: 418, height: 235 });
suggestion: put these values in constants.

2022-11-16 18:01 UTC, paulschreiber requested changes

2022-11-16 18:01 UTC, paulschreiber commented on src/landscape/components/LandscapeProfile/ProfileCard.js
> +            : '/landscape/profile-image-default.jpg'
suggestion: put this in a constant.

2022-11-17 16:13 UTC, merged