Feat/story map delete
techmatters/terraso-web-client pull request #790
Opened 2023-03-20 17:10 UTC by josebui

## Description

- Delete Story Map button added

### Checklist
- [ ] Corresponding issue has been opened
- [ ] New tests added

### Related Issues
Fixes #....

### Verification steps

2023-03-20 17:58 UTC, paulschreiber requested changes

2023-03-20 17:58 UTC, paulschreiber commented on src/localization/locales/en-US.json
> +        "deleted_story_map": "<strong>{{title}}</strong> is deleted",
```suggestion
        "deleted_story_map": "<strong>{{title}}</strong> was deleted",
```

2023-03-20 17:58 UTC, paulschreiber commented on src/localization/locales/en-US.json
> +        "delete_confirm_message": "You cannot undo deleting your story map. Deleting your published story map may cause a missing page error to your story map viewers.",
```suggestion
        "delete_confirm_message": "Are you sure you wish to delete the story map? This cannot be undone.,
```
Should match other deletion text.

2023-03-20 17:58 UTC, paulschreiber commented on src/localization/locales/en-US.json
> +        "delete_confirm_title": "Delete {{title}} story map?",
```suggestion
        "delete_confirm_title": "Delete story map {{title}}?",
```

2023-03-20 17:58 UTC, paulschreiber commented on src/storyMap/components/UserStoryMap.js
> +  const onDeleteSuccess = useCallback(() => navigate('/'), [navigate]);
question: does this go back to root? I would expect to go back to the Story Maps page.

2023-03-20 21:31 UTC, paulschreiber approved these changes

2023-03-21 15:22 UTC, merged

2023-03-22 13:41 UTC, DerekCaelin commented
### Tested:

**Creation**
- [x] Created story map
- [x] Filled text box with 5000 characters
- [x] Swapped between image and youtube video
- [x] Create story map with all special characters in the title
- [ ] Create story map with all spaces in the title

**Deletion**
- [x] Delete story map (eng)
- [ ] Delete story map (es) #736 
- [x] deleted story map should be inaccessible to view
- [x] deleted story map should be inaccessible to edit
- [x] can't edit someone else's story map